# Generated by Django 5.1.7 on 2025-07-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_alter_address_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='iventory',
            new_name='inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
